### ISSUE TITLE
CRDs loading error

### ISSUE THREAD

**Issue by wwitzel3** [vmware/octant#54]
@mdaverde commented on [Thu Jul 11 2019](https://github.com/heptio/developer-dash/issues/853)

When I click on a my CRD from the CRD list view, I see this in the terminal console:

```
E0711 16:11:23.428224   89205 reflector.go:134] github.com/vmware/octant/third_party/k8s.io/client-go/dynamic/dynamicinformer/informer.go:89: Failed to list *unstructured.Unstructured: Stream error http2.StreamError{StreamID:0x4e1, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
E0711 16:11:28.471659   89205 reflector.go:134] github.com/vmware/octant/third_party/k8s.io/client-go/dynamic/dynamicinformer/informer.go:89: Failed to list *unstructured.Unstructured: Stream error http2.StreamError{StreamID:0x539, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
E0711 16:12:35.546751   89205 reflector.go:134] github.com/vmware/octant/third_party/k8s.io/client-go/dynamic/dynamicinformer/informer.go:89: Failed to list *unstructured.Unstructured: Stream error http2.StreamError{StreamID:0x605, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
```

Nothing in the UI console. This error causes the UI to hang, never going to the specific detail CRD page.

---

@bryanl commented on [Mon Jul 22 2019](https://github.com/heptio/developer-dash/issues/853#issuecomment-510648816)

This isn't a CRD issue. It's a cluster connectivity issue. Notice the log is from klog. Octant will retry a few times, but will quit after five times.

---

@mdaverde commented on [Mon Jul 15 2019](https://github.com/heptio/developer-dash/issues/853#issuecomment-511400915)

The `Failed to list *unstructured.Unstructured: Stream error http2.StreamError{StreamID:0x4e1, Code:0x2, Cause:error(nil)}` part makes it seem it's an internal issue. The messaging here should change.

---

@bryanl commented on [Mon Jul 15 2019](https://github.com/heptio/developer-dash/issues/853#issuecomment-511404141)

This is a client go reported error. All we could potentially do is turn down the logging verbosity. 

---

@mdaverde commented on [Mon Jul 15 2019](https://github.com/heptio/developer-dash/issues/853#issuecomment-511445585)

If this error is a cluster connectivity error, then I wouldn't propagate this client-go error to the Octant user and instead say something that means "This is a cluster connectivity error. Here are the action steps to debug/verify/fix..."

---

@bryanl commented on [Mon Jul 22 2019](https://github.com/heptio/developer-dash/issues/853#issuecomment-511447733)

Yes, this is true. My original comment was that this isn't a CRD issue. I'll remove that label.

---

@mdaverde commented on [Mon Jul 22 2019](https://github.com/heptio/developer-dash/issues/853#issuecomment-511578483)

I'm not sure this is a cluster connectivity issue, given that I can run `kubectl describe crd/{{crd name}}` with a quick response time in comparison to the UI.

To emphasize: the UI never resolves.

---

@mdaverde commented on [Mon Jul 22 2019](https://github.com/heptio/developer-dash/issues/853#issuecomment-512949854)

Observation: looks to be each CRD detail view results in theses errors being shown:

```
E0718 15:11:41.729079   78466 reflector.go:134] github.com/vmware/octant/third_party/k8s.io/client-go/dynamic/dynamicinformer/informer.go:89: Failed to list *unstructured.Unstructured: Stream error http2.StreamError{StreamID:0x4db, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
E0718 15:12:26.813312   78466 reflector.go:134] github.com/vmware/octant/third_party/k8s.io/client-go/dynamic/dynamicinformer/informer.go:89: Failed to list *unstructured.Unstructured: Stream error http2.StreamError{StreamID:0x461, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
E0718 15:12:29.497056   78466 reflector.go:134] github.com/vmware/octant/third_party/k8s.io/client-go/dynamic/dynamicinformer/informer.go:89: Failed to list *unstructured.Unstructured: Stream error http2.StreamError{StreamID:0x4d3, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
```

**Comment by wwitzel3** [comment]
@mdaverde we merged some things that adjusted our rate limiting and calls and things are loading much much faster now and I'm not seeing these types of errors like I was before. Would you mind re-testing this and seeing if they've cleared up for you as well?

**Comment by mdaverde** [comment]
I'm still seeing these logs come through, but the UI is now resolving. We can close this issue and I'll file more specific breaking issues. Thanks
